global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Linq;
global using HarmonyLib;
global using UnityEngine;
global using UnityEngine.UI;
global using static UnityEngine.Object;
global using Object = UnityEngine.Object;
global using Random = UnityEngine.Random;
global using static UnityEngine.ScriptableObject;
global using ScriptableObject = UnityEngine.ScriptableObject;
global using static UnityEngine.ScriptableObject;
global using JFUtils;
global using JFUtils.Valheim;
global using JFUtils.Valheim.WithPatch;
global using static ZoneSystem;
global using static JFUtils.Valheim.ModBase;
global using static ZoneSystem.ZoneLocation;
global using static ZoneSystem.ZoneVegetation;
global using static Heightmap;
global using static Heightmap.Biome;
global using static ItemDrop;
global using static ItemDrop.ItemData;
global using static Summoner.Plugin;
global using static BepInEx.BepInDependency;
global using static Skills;
global using static Minimap.MapMode;
global using static Minimap;
global using StringBuilder = System.Text.StringBuilder;
global using ConsoleCommand = Terminal.ConsoleCommand;
global using Stopwatch = System.Diagnostics.Stopwatch;
global using BepInEx.Configuration;
using JetBrains;
using JetBrains.Annotations;